### ISSUE TITLE
Xinput plugin

### ISSUE THREAD

**Issue by gasdia73** [sezanzeb/key-mapper#110]
I have some settings on my mouse with xinput:

xinput --set-prop 10 "libinput Accel Profile Enabled" 1 0
xinput --set-prop 10 "libinput Accel Speed" 0.6
xinput --set-prop 10 'Coordinate Transformation Matrix' 0.6 0 0 0 0.6 0 0 0 0.6

and I've installed key-mapper to assign some key combos to left and right wheel button, and it works, but
when I reboot the xinput settings above are not applied anymore

**Comment by sezanzeb** [comment]
probably because it grabs the device, so the device id 10 cannot be used by xinput anymore.

try `xinput list` and search for a devices prefixed with "mapped" and "forwarded", you need to use those device ids.

Since I don't use xinput, those are just wild guesses. Anyway, key-mapper was not designed to work well with other tools. But if plugin support is ever available, a plugin could be offered to apply xinput commands when the injection starts automatically for all new uinputs.

**Comment by sezanzeb** [comment]
see https://github.com/sezanzeb/key-mapper/issues/24#issuecomment-762997041

**Comment by gasdia73** [comment]
ok I'm going to try what is suggested there, thank you
