### ISSUE TITLE
How to map ctrl hjkl as arrow keys

### ISSUE THREAD

**Issue by fecet** [sezanzeb/key-mapper#126]
I simply try ctrl hjkl as arrows and ctrl+jk works fine but ctrl hl are works like:
ctrl+left or ctrl+right
which will skip a word. Then I try to map: ctrl+left as "disable" then that just make the ctrl h has no effect.
How to let then work as desired?

**Comment by sezanzeb** [comment]
can you make a screenshot of you mapping please?

**Comment by fecet** [comment]
![image](https://user-images.githubusercontent.com/41792945/121929160-7c94ed00-cd73-11eb-8d7b-c4a66d0a97b5.png)

**Comment by sezanzeb** [comment]
ah, and what would ctrl + jk be mapped to?

I believe you would have to disable "Control L" for it to work. This is because the environment sees your injected "Left" and also knows that "Control" is held down. Therefore it will interpret the incoming events as "ctrl + left". This is why the following warning is displayed:

![image](https://user-images.githubusercontent.com/28510156/121947761-b86d8980-cd56-11eb-9c79-185ca449b90a.png)

**Comment by sarimak** [comment]
I have a trackball with scroll ring (Kensington Expert Mouse) and still find it useful to map unused keys to scroll down/up and left click via key-mapper. I use PrtSc for scroll up, ScrLk for left click and Pause for scroll down. I operate the trackball by left hand and have a tenkeyless keyboard layout so those 3 buttons are easily accessible with pinkie resting on the table and scrolling using a thumb -- or by placing index+middle+ring fingers on those 3 keys and with forearm resting on a keyboard palmrest.

So while it doesn't solve the technical issue you encountered, you might be interested in trying a different arrangement for reducing the strain caused by scrolling.

**Comment by sezanzeb** [comment]
Feel free to reopen the issue if you have any more questions :)
