### ISSUE TITLE
OpenRC init script needed

### ISSUE THREAD

**Issue by proton252** [sezanzeb/key-mapper#15]
Hi, if possible please add open-rc init script, thanks.

**Comment by sezanzeb** [comment]
I would accept a pull request that provides this script (as well as for sysv init). All my installations use systemd.

**Comment by proton252** [comment]
Sorry my poor English, already writed script working with Atrix OpenRc. 
```
#!/sbin/openrc-run
# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="Daemon for key-mapper-service"
start() {
    ebegin "key-mapper service"
    start-stop-daemon --background --start --exec /usr/bin/key-mapper-service \
    --make-pidfile --pidfile /tmp/key-mapper.pid
    eend $?
}
#notice the bash like escape to use newlines
depend() {
	need dbus
}
```

**Comment by M8850** [comment]
for runit it's: 

`$ cat run

#!/bin/sh
sv check dbus > /dev/null || exit 1
exec /usr/bin/input-remapper-service > /dev/null 2>&1`

**Comment by arscynic** [comment]
> Sorry my poor English, already writed script working with Atrix OpenRc.
> […]

Updated for my current Artix Linux:

1. Create the file `/etc/init.d/input-remapper` with the content below:

```
#!/sbin/openrc-run
# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="Daemon for input-remapper-service"
start() {
    ebegin "input-remapper service"
    start-stop-daemon --background --start --exec /usr/bin/input-remapper-service \
    --make-pidfile --pidfile /tmp/input-remapper.pid
    eend $?
}
#notice the bash like escape to use newlines
depend() {
	need dbus
}
```

2. Make it executable: `sudo chmod +x /etc/init.d/input-remapper`
3. Add the service: `sudo rc-update add input-remapper default`
4. Start the service: `sudo rc-service input-remapper start`

I've only just began using _OpenRC_ as init system, and have no idea whether the service script above is written according to a proper standard, because it looks way different to the script that gets added by default when one installs `keyd-openrc` via the AUR:
```
#!/sbin/openrc-run

name=$RC_SVCNAME
description="A key remapping deamon"

command="/usr/bin/keyd"
command_background="yes"
pidfile="/run/$RC_SVCNAME.pid"
output_log="/var/log/keyd.log"
error_log="/var/log/keyd.err"

depend() {
	need localmount dev-mount
}
```
