### ISSUE TITLE
[Req] Priority setting / Ordering precedence of mappings

### ISSUE THREAD

**Issue by Gotolei** [sezanzeb/key-mapper#159]
In short, these are my mappings on an elecom huge. `Button TASK` is fn3, `FORWARD` and `BACK` are fn1 and fn2 respectively:
![image](https://user-images.githubusercontent.com/7553595/128085586-0b9feab3-667a-4857-9e4a-6fb45a694c98.png)
The shortcuts for media controls function just fine, including correctly not triggering the volume keys if fn3 `TASK` is held, but it always sends a middle-button click when fn3 is released whether another shortcut has been activated or not. Frequently this leads to random middle-click pasting in focused windows with a text field active.

As far as I'm aware, the built-in scripting system doesn't have a way to check that button x is the only button being pressed (and if it does I'm all ears), but to me it looks like one of the most-understandable ways to handle this would be either of these:
- Definable priorities for each mapping: if a mapping has been triggered by a chord, only mappings of the same priority or above can be matched until all common buttons are released
- Have the ordering of the mappings matter: once a mapping has been matched, only that mapping and those above it can be matched until all common buttons are released

**Comment by sezanzeb** [comment]
> it always sends a middle-button click when fn3 is released whether another shortcut has been activated or not

The order is like this:

1. the fn3 button is pressed with your finger, `TASK 1` arrives via evdev in key-mapper
2. key-mapper maps it to `BTN_MIDDLE 1` and injects it
3. some other button is pressed with your finger, `BACK 1` arrives via evdev in key-mapper
4. key-mapper maps it to `XF84AudioPrev 1` and injects it
5. some other button is released, `BACK 0` arrives at key-mapper
6. key-mapper maps that release to `XF84AudioPrev 0` and injects it
7. the fn3 button is released, `TASK 0` arrives at key-mapper
8. key-mapper maps that release to `BTN_MIDDLE 0` and injects it

so BTN_MIDDLE 1 (down) has already been injected, it does not happen on release

and it definitely has to send BTN_MIDDLE 0 (up) at some point, otherwise it would never release and be held down forever.

**Comment by sezanzeb** [comment]
feel free to reopen if you still think there is an issue. As far as I can tell this is expected behavior
