### ISSUE TITLE
macropad (duckyPad) shown as mouse device

### ISSUE THREAD

**Issue by jose1711** [sezanzeb/key-mapper#202]
Inside the GUI [duckyPad](https://duckypad.io/) macropad appears as `dekuNukem duckyPad(2020) Mouse` which is a bit weird since while it can emulate mouse events it is not definitely its primary function. This looks to be more cosmetics because the keyboard presses (and also mouse clicks) are registered correctly.

```
evtest 2>&1 | grep duckyPad
/dev/input/event24:	dekuNukem duckyPad(2020) Keyboard
/dev/input/event25:	dekuNukem duckyPad(2020) Mouse
/dev/input/event26:	dekuNukem duckyPad(2020)

```

**Comment by sezanzeb** [comment]
As far as I remember this is because there is a certain priority in detecting the device type

All mice, gamepads, graphics tablets, etc. support EV_KEY events, which would be enough to classify it as keyboard

but since they also support
- BTN_LEFT, REL_X, REL_WHEEL, ... (mouse)
- BTN_A, ABS_RX, ... (gamepad)
- BTN_STYLUS, ... (tablet)

they are not classified as keyboard

Since duckyPad seems to have a mouse device ready at all times which will apparently only sends events to linux when the mouse emulation mode is active, there will always be REL_X, REL_WHEEL, ... capabilities. Linux doesn't know if the duckyPad is in said mode.

I don't think the classification as mouse has side effects, but if a device is classified as gamepad it certainly has. The classification as mouse might be needed in the far future for some special features that are only possible on a mouse.

**Comment by sezanzeb** [comment]
This is a valid objection, but impossible for key-mapper to see without knowing what is going on beyond the usb port.
