### ISSUE TITLE
Can we map a key to arbitrary unicode char?

### ISSUE THREAD

**Issue by academay** [sezanzeb/key-mapper#209]
Sometimes I just to type a certain character,  regardless of keyboard layout(s).
e.g. a coin symbol, frequent emoji, etc.

Is that possible? Can it be made possible?

(I tried to assign key(🫒), or just 🫒, but got an error of course).

(KDE keyboard shortcuts has bug with unicode shortcuts, otherwise i'd accomplish it with the DE tools)

**Comment by sezanzeb** [comment]
No unfortunately this is not possible, since key-mapper acts like a keyboard. Key-mapper can only do things that a keyboard could potentially do.

The environment decides how keycodes are interpreted. For example the code 30 is used for the letter "a", which depends on the keyboard layout that is configured in your environment. But in those layout configs there is no key that is used for emoji input.

**Comment by sezanzeb** [comment]
but you might be able to write a macro that does a special shortcut.

Use this with caution! If the currently used tool in focus decides to not support this shortcut (And I think this is something that only works in GTK apps) then you will potentially trigger lots of shortcuts. `m(Control_L, m(Shift_L, k(u).k(1).k(f).k(6).k(0).k(0)))` for 😀
