### ISSUE TITLE
Mapping preset change

### ISSUE THREAD

**Issue by Kierek** [sezanzeb/key-mapper#72]
For starters, thank you so much for this app, it's very useful.

Is it possible to set mapping as a preset selection? I can see options like "key_macro_preset_cycle" are available, but I don't think they do what I want.

I'd like to have multiple different presets, with one "switcher" preset, where every button is mapped to selecting different preset. Some kind of "programming mode". Is it already possible and I'm missing something here?

**Comment by sezanzeb** [comment]
Thanks.

no, not possible

switching presets would currently require the injections processes to start again, which is very slow.

**Comment by Kierek** [comment]
I wouldn't mind slow switching, it's still better than having to open application and change it manually.

**Comment by sezanzeb** [comment]
I'd rather first check if there is a way to make preset switching work without grabbing the devices from scratch.

If any key is held down in the wrong moment when applying a preset they will never release, because the original device that sent the key-down event won't be able to send any new events once grabbed. There is a check for that in the gui that prevents applying the preset in that case.

The solution would be to not create any uinput device again that already exists and to not ungrab any device that needs to be grabbed again.

**Comment by matt-hu** [comment]
I have had a idea that might work, more so for the concept of layers rather than presets. If you were to map your switching key (for example, an alt or ctrl key) to hyper (ctrl + alt + shift + super), then map all your "second layer" keys to include hyper key. For example, you could map hyper + w to be the up arrow.

The only other thing needed would be a way to toggle a key or make it "sticky" like sticky keys on Windows. This way you could use the key you have mapped to hyper to toggle between "layers".

Not sure if this helps but I hope it at least makes sense?

**Comment by sezanzeb** [comment]
you could try setting up keyboard shortcuts for the CLI in your desktop environments settings:

https://github.com/sezanzeb/key-mapper/blob/main/readme/usage.md#cli

but what it's still a bit dangerous, no optimization on grabbing and creating uinputs has been implemented yet.

**Comment by sezanzeb** [comment]
switching presets via the cli will be safer in that regard now. The time frame in which the problem is reproducible should be a lot smaller now

**Comment by dtruesdale88** [comment]
This is what I am looking for to use with the Tartarus with the scroll wheel to change keyboard layers, there is suppose to be 3 each with a corresponding led on the side to which layer you are using. Is this possible?

**Comment by sezanzeb** [comment]
I doubt the LEDs can be controlled from the computer.

Using the scroll wheel to toggle between 3 different mappings will require some somewhat complicated macros (see https://github.com/sezanzeb/key-mapper/issues/91#issuecomment-826360430 for using 2 different "layers")
