### ISSUE TITLE
ModuleNotFoundError after pip installation in Fedora

### ISSUE THREAD

**Issue by byron-hawkins** [sezanzeb/key-mapper#85]
I could only install via `pip3` as root, but now I can only run the key-mapper apps as root. When I run as a regular user, I get this:

    Traceback (most recent call last):
      File "/usr/bin/key-mapper-gtk", line 37, in <module>
        from keymapper.logger import update_verbosity, log_info
    ModuleNotFoundError: No module named 'keymapper'

Attempting to find the python paths for key-mapper yielded nothing (`find`, `locate` after `updatedb`, etc), so I can't update my `PYTHONPATH` or anything else. It sounds like python expertise is required to run this program, which seems contradictory to the fancy UI and nice documentation. Is this really intended? (If it has any relevance to the credibility of my suggestion, I have a PhD in Computer Engineering, but I don't use python often).

**Comment by sezanzeb** [comment]
> Is this really intended?

no

which distro?

please run this to see where the module is

```
sudo python3
>>> import keymapper
>>> keymapper.__file__
```

and run this to see where valid locations would be on your system

```
python3
>>> import sys
>>> sys.path
```

**Comment by byron-hawkins** [comment]
> python3 -c "import keymapper; print(keymapper.__file__)"
    /root/.local/lib/python3.8/site-packages/keymapper/__init__.py

    > python3 -c "import sys; print('\n'.join(sys.path))"

    /usr/lib64/python38.zip
    /usr/lib64/python3.8
    /usr/lib64/python3.8/lib-dynload
    /usr/local/lib/python3.8/site-packages
    /usr/lib64/python3.8/site-packages
    /usr/lib/python3.8/site-packages

**Comment by sezanzeb** [comment]
which distro?

I know that ubuntu screws the pip installation up (installs to /usr/local/lib instead of /usr/lib), I can't rule out that other distros fail as well. Seems to be the case here. I don't know why that would happen and how to overwrite that behavior.

It needs to run as root because certain files are copied around to special locations in setup.py, and because the code is run as root via systemd and therefore it can't be within user directories and it certainly shouldn't be editable by non-root users.

**Comment by byron-hawkins** [comment]
Fedora 32 here, vanilla install. So I dunno what to suggest.

**Comment by sezanzeb** [comment]
Ah ok. Lets hope that https://github.com/sezanzeb/key-mapper/issues/83 works out then.

You could try to use `sudo python3 setup.py install`, but uninstalling will only work via `sudo find /usr -iname "key*mapper*" -exec rm {} -r \;` afterwards.

**Comment by byron-hawkins** [comment]
It's actually fine for me to run the apps as root on my current network, since the configuration persists globally. But at the office, the desktops are managed by the IT group and I don't have root, so even installing keymapper would not be possible. For the moment I'm not using desktops and anyway the office is closed, though it could become a limitation at some point. If it's possible to add a single-user mode for the installer, that would likely be convenient for anyone in a similar situation.

**Comment by sezanzeb** [comment]
key-mapper needs to access device nodes in /dev/input, so a non-root mode is not possible.

The only option would be to somehow get yourself into the input group, but the code would need to be modified as well to not call pkexec anymore.

Since an issue for rpm packaging already exists, should I close this issue then?
